const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const dom=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.com/npcbeta/',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};
 const legacy={id:'generated-legacy',name:'Old Friend',locationId:'tavern-inn',professionId:'innkeeper',locationLabel:'Legacy label',professionLabel:'Legacy role',createdAt:'2026-01-01'};
 w.localStorage.setItem('npc-beta:generator:v1:session',JSON.stringify([legacy]));w.localStorage.setItem('npc-beta-saved','["mira-fen"]');w.localStorage.setItem('npc-beta-session','["cassian-holt"]');
 w.fetch=async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('docs/'+path))});
 w.eval(['portraits','character-portraits','generator','locations','generated-visuals','session-board','app'].map(n=>fs.readFileSync('docs/js/'+n+'.js','utf8')).join('\n')+'\nwindow.test={setView,ensureGenerator,ensureLocations,rollGenerator,generator,generatedNpcVisual,GENERATED_LOCATION_TEMPLATES};');
 await new Promise(r=>setTimeout(r,20));const t=w.test,d=w.document;t.setView('generator');await t.ensureGenerator();await t.ensureLocations();
 const options=JSON.parse(fs.readFileSync('docs/data/generator/options.json')),templates=JSON.parse(fs.readFileSync('docs/data/locations/templates.json'));
 for(const location of options.locations){assert(Object.hasOwn(t.GENERATED_LOCATION_TEMPLATES,location.id));const mapped=t.GENERATED_LOCATION_TEMPLATES[location.id];assert(mapped && templates.some(x=>x.id===mapped && x.image));}
 const cast=d.querySelector('#cast-list .generated-npc-visual');assert(cast.querySelector('img').src.endsWith('/images/locations/tavern.webp'));assert.equal(cast.getAttribute('aria-hidden'),'true');assert.equal(cast.querySelector('.generated-npc-silhouette').getAttribute('src'),'images/generated-npc-silhouette.svg');assert.equal(cast.querySelector('.generated-npc-silhouette').alt,'');assert.equal(cast.querySelector('img').alt,'');assert(d.querySelector('#cast-list .cast-portrait'));assert.equal(d.querySelector('#cast-list .cast-entry').lastChild.tagName,'DIV');
 t.rollGenerator('location','marketplace');t.rollGenerator('profession','merchant');const preview=()=>d.querySelector('#generator-visual-preview .generated-npc-visual');assert(preview().querySelector('img').src.endsWith('/market-square.webp'));const before=preview().innerHTML;t.rollGenerator('name');assert.equal(preview().innerHTML,before);
 t.rollGenerator('profession','guard');assert.notEqual(preview().innerHTML,before);t.rollGenerator('location','tavern-inn');assert(preview().querySelector('img').src.endsWith('/tavern.webp'));const result=JSON.parse(JSON.stringify(t.generator.current));d.querySelector('#add-generated').click();const companion=d.querySelector('#cast-list .cast-entry:last-child .generated-npc-visual').innerHTML;t.setView('session');assert.equal([...d.querySelectorAll('#character-grid .cast-entry')].find(card=>card.querySelector('h3').textContent===result.name).querySelector('.generated-npc-visual').innerHTML,companion);assert(d.querySelector('#character-grid .session-portrait'));assert.equal(t.generator.records.at(-1).locationId,result.locationId);assert.equal(t.generator.records.at(-1).professionId,result.professionId);
 const unknown=t.generatedNpcVisual({locationId:'unknown',professionId:'unknown'});assert(!unknown.querySelector('.generated-visual-background img'));assert(unknown.querySelector('.generated-npc-silhouette'));assert(unknown.querySelector('.generated-location-symbol'));assert(unknown.querySelector('.generated-profession-badge svg'));const ship=t.generatedNpcVisual({locationId:'ship',professionId:'sailor'});assert(ship.querySelector('.generated-visual-background img').src.endsWith('/ship-location.webp'));assert(ship.querySelector('.generated-npc-silhouette'));const broken=t.generatedNpcVisual(legacy);broken.querySelector('img').dispatchEvent(new w.Event('error'));assert(!broken.querySelector('.generated-visual-background img'));assert(broken.querySelector('.generated-npc-silhouette'));assert(broken.querySelector('.generated-location-symbol'));assert(broken.querySelector('.generated-profession-badge'));
 assert.deepEqual(JSON.parse(w.localStorage.getItem('npc-beta:generator:v1:session'))[0],legacy);assert.equal(w.localStorage.getItem('npc-beta-saved'),'["mira-fen"]');assert.equal(w.localStorage.getItem('npc-beta-session'),'["cassian-holt"]');assert(!w.localStorage.getItem('npc-beta:generator:v1:session').includes('images/'));dom.window.close();console.log('PASS: explicit mappings, legacy records, both card renderers, portraits, all rerolls, identical saved visual, decorative markup, missing/broken artwork and unknown profession fallbacks, storage preservation');
})().catch(e=>{console.error(e);process.exit(1)});
