const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.NPC_TEST_CHROME,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://localhost:8000/**',async route=>{const path=new URL(route.request().url()).pathname,file='.'+(path.endsWith('/')?path+'index.html':path),ext=file.split('.').pop();await route.fulfill({status:fs.existsSync(file)?200:404,contentType:({js:'text/javascript',css:'text/css',json:'application/json',svg:'image/svg+xml',webp:'image/webp'})[ext]||'text/html',body:fs.existsSync(file)?fs.readFileSync(file):'Not found'});});
await page.goto('http://localhost:8000/docs/#locations');await page.waitForSelector('.location-card');
await page.evaluate(()=>{localStorage.setItem('npc-beta-saved','["mira-fen"]');localStorage.setItem('npc-beta-session','["mira-fen"]');});
const card=page.locator('[data-template-id="inn"]');await card.locator('.location-card-open').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#detail-title').textContent(),'Inn');
assert.deepEqual(await page.locator('.detail-location-reference h3').evaluateAll(ns=>ns.map(n=>n.firstChild.textContent)),['Description','More Flavour','Discovery']);assert(await page.locator('.location-flavour p').isVisible());assert(await page.locator('.location-discovery p').isVisible());assert(await page.locator('.location-detail-actions button').isVisible());assert(await page.locator('.session-button').isHidden());
const help=page.locator('.flavour-help-button'),tip=page.locator('#flavour-help-tooltip');assert.equal(await tip.textContent(),'Optional detail to read when you have more time.');assert(await tip.isHidden());await help.hover();assert(await tip.isVisible());await page.locator('#detail-title').hover();assert(await tip.isHidden());await page.keyboard.press('Tab');await help.focus();assert(await tip.isVisible());await page.keyboard.press('Escape');assert(await tip.isHidden());assert.equal(await page.locator('#detail-panel').getAttribute('aria-hidden'),'false');
await page.locator('.location-detail-actions button').click();await page.locator('.location-detail-actions button').click();const instances=await page.evaluate(()=>JSON.parse(localStorage.getItem('npc-beta:locations:v1:session')));assert.equal(instances.length,2);assert.notEqual(instances[0].id,instances[1].id);
assert(await page.locator('.location-introduction p').evaluate(n=>parseFloat(getComputedStyle(n).fontSize))>await page.locator('.location-flavour p').evaluate(n=>parseFloat(getComputedStyle(n).fontSize)));
await page.locator('.detail-scroll').evaluate(n=>n.scrollTop=n.scrollHeight);await page.locator('.back-button').click();await card.locator('.location-card-open').click();assert.equal(await page.locator('.detail-scroll').evaluate(n=>n.scrollTop),0);await page.waitForTimeout(400);await page.evaluate(()=>{clearTimeout(announce.timer);document.querySelector('#action-feedback').textContent='';});fs.mkdirSync('project/screenshots',{recursive:true});await page.screenshot({path:'project/screenshots/location-detail-desktop.png'});
await page.locator('.back-button').click();await page.evaluate(()=>setView('session'));await page.locator('#session-location-list .session-row-open').first().click();assert.equal(await page.locator('.location-detail-actions').count(),0);assert(await page.locator('.session-button').isHidden());await page.locator('[data-location-field=notes]').fill('Personal notes remain separate');await page.locator('[data-location-field=displayName]').fill('My Silver Fox');await page.locator('[data-location-field=condition]').selectOption('ruined');assert.equal(await page.locator('#detail-title').textContent(),'My Silver Fox');assert((await page.locator('.tag-list').textContent()).includes('Ruined'));await page.locator('.back-button').click();await page.reload();await page.waitForSelector('#session-npc-column .session-row');await page.locator('#session-location-list .session-row-open').first().click();assert.equal(await page.locator('[data-location-field=notes]').inputValue(),'Personal notes remain separate');assert.equal(await page.locator('#detail-title').textContent(),'My Silver Fox');assert.equal(await page.locator('.detail-scroll').evaluate(n=>n.scrollTop),0);
await page.setViewportSize({width:390,height:844});await page.locator('.detail-scroll').evaluate(n=>n.scrollTop=0);await help.tap();assert(await tip.isVisible());assert.equal(await help.getAttribute('aria-expanded'),'true');await help.tap();assert(await tip.isHidden());await help.tap();assert(await tip.isVisible());const bounds=await tip.boundingBox();assert(bounds.x>=0 && bounds.x+bounds.width<=390);await page.screenshot({path:'project/screenshots/location-detail-mobile.png'});await page.locator('#detail-title').tap();assert(await tip.isHidden());
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);assert(await help.evaluate(n=>n.getBoundingClientRect().height)>=44);}
assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('npc-beta-saved'),localStorage.getItem('npc-beta-session')]),['["mira-fen"]','["mira-fen"]']);await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.detail-panel').evaluate(n=>getComputedStyle(n).transitionDuration),'0s');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: shared library/Session details, keyboard opening, exact hover/focus/tap tooltip and Escape dismissal, section order/prominence, duplicate Add actions, scroll reset, notes/name/condition persistence, 320–1440px layout, touch targets, reduced motion and unchanged NPC storage');
})().catch(e=>{console.error(e);process.exit(1)});
