const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
(async()=>{
 const templates=JSON.parse(fs.readFileSync('docs/data/locations/templates.json')),base=JSON.parse(execFileSync('git',['show','origin/main:docs/data/locations/templates.json'],{encoding:'utf8'}));
 assert.equal(templates.length,44);assert.deepEqual(templates.map(({flavour,discovery,...old})=>old),base);
 for(const item of templates){assert.equal(item.flavour.split(/(?<=[.!?])\s+/).length,2,item.id);assert([1,2].includes(item.discovery.split(/(?<=[.!?])\s+/).length),item.id);assert(!Object.hasOwn(item,'complication'));}
 const dom=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.com/#locations',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};
 const old=[{id:'location-legacy',templateId:'inn',displayName:'Personal Inn',notes:'Keep my notes <script>unchanged</script>',settings:['village'],condition:'ruined',createdAt:'2026-01-01'}];w.localStorage.setItem('npc-beta:locations:v1:session',JSON.stringify(old));w.localStorage.setItem('npc-beta-session','["mira-fen"]');w.localStorage.setItem('npc-beta-saved','["mira-fen"]');
 w.fetch=async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('docs/'+path))});w.eval(['portraits','character-portraits','generator','locations','generated-visuals','session-board','app'].map(n=>fs.readFileSync('docs/js/'+n+'.js','utf8')).join('\n')+'\nwindow.test={openLocationDetail,locationLibrary,setView,openDetail,state,validateLocationData};');await new Promise(r=>setTimeout(r,30));const d=w.document,t=w.test;
 for(const template of templates){t.openLocationDetail(template.id);assert.equal(d.querySelector('#detail-title').textContent,template.name);assert.equal(d.querySelector('.location-introduction p').textContent,template.description.split(/(?<=[.!?])\s+/)[0]);assert.equal(d.querySelector('.location-flavour p').textContent,template.flavour);assert.equal(d.querySelector('.location-discovery p').textContent,template.discovery);assert.deepEqual([...d.querySelectorAll('.detail-location-reference h3')].map(n=>n.firstChild.textContent),['Description','More Flavour','Discovery']);assert(d.querySelector('.location-detail-actions button'));assert(d.querySelector('.session-button').hidden);assert.equal(d.querySelector('.detail-scroll').scrollTop,0);}
 const legacy={...templates[0]};delete legacy.flavour;delete legacy.discovery;t.validateLocationData([legacy],t.locationLibrary.labels);t.locationLibrary.templates=[legacy];t.openLocationDetail('inn');assert.match(d.querySelector('.location-flavour p').textContent,/No additional/);assert.match(d.querySelector('.location-discovery p').textContent,/No discovery/);
 t.setView('session');d.querySelector('#session-location-list .session-row-open').click();assert.equal(d.querySelector('#detail-title').textContent,'Personal Inn');assert.equal(d.querySelector('.tag-list').textContent,'VillageRuined');assert(!d.querySelector('.location-detail-actions'));assert.equal(d.querySelector('[data-location-field=notes]').value,old[0].notes);assert.equal(w.localStorage.getItem('npc-beta:locations:v1:session'),JSON.stringify(old));
 t.openLocationDetail('missing',old[0]);assert.match(d.querySelector('.location-introduction p').textContent,/unavailable/);assert.equal(d.querySelector('[data-location-field=notes]').value,old[0].notes);
 t.openDetail(t.state.characters.find(x=>x.id==='mira-fen'));assert(d.querySelector('.detail-location-reference').hidden);assert(!d.querySelector('.detail-summary').hidden);assert.equal(w.localStorage.getItem('npc-beta-saved'),'["mira-fen"]');assert.equal(w.localStorage.getItem('npc-beta-session'),'["mira-fen"]');dom.window.close();console.log('PASS: 44 complete locations/sentence counts, original metadata/descriptions/order, shared sections/actions/tags, legacy/missing field fallback, NPC panel reset and unchanged existing storage');
})().catch(e=>{console.error(e);process.exit(1)});
