const {JSDOM}=require('jsdom');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const templates=JSON.parse(fs.readFileSync('docs/data/locations/templates.json'));
const labels=JSON.parse(fs.readFileSync('docs/data/locations/labels.json'));
const seed={'npc-beta-saved':'["mira-fen"]','npc-beta-session':'["cassian-holt"]'};
async function setup(storage=seed,failure){
 const dom=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'http://localhost/npcbeta/',runScripts:'outside-only'});const w=dom.window;w.scrollTo=()=>{};
 w.fetch=async url=>({ok:!(failure==='data'&&url.includes('locations/')),json:async()=>JSON.parse(fs.readFileSync('docs/'+url,'utf8'))});
 for(const[k,v]of Object.entries(storage))w.localStorage.setItem(k,v);
 if(failure==='storage'){w.Storage.prototype.setItem=()=>{throw Error('quota')};}
 if(failure==='unavailable'){w.Storage.prototype.getItem=()=>{throw Error('blocked')};w.Storage.prototype.setItem=()=>{throw Error('blocked')};}
 w.eval(['generator','locations','generated-visuals','app'].map(file=>fs.readFileSync('docs/js/'+file+'.js','utf8')).join('\n')+'\nwindow.test={locationLibrary,validateLocationData,visibleLocations,clearLocationFilters,addSessionLocation,renderSessionLocations,safeLocationImage,setView,ensureLocations,ensureGenerator,generator,state,sessionEntries};');
 await new Promise(r=>setTimeout(r,10));w.test.setView('locations');await w.test.ensureLocations();return dom;
}
(async()=>{
 const dom=await setup(),w=dom.window,t=w.test,l=t.locationLibrary;
 assert.equal(templates.length,templates.length);t.validateLocationData(templates,labels);assert.equal(new Set(templates.map(x=>x.id)).size,templates.length);assert.equal(w.document.querySelectorAll('.location-card').length,templates.length);
 assert.throws(()=>t.validateLocationData([...templates,templates[0]],labels));assert.throws(()=>t.validateLocationData([{...templates[0],condition:'broken'}],labels));assert.throws(()=>t.validateLocationData([{...templates[0],settings:[]}],labels));
 for(const item of templates)for(const setting of item.settings){l.settings.clear();l.settings.add(setting);assert(t.visibleLocations().some(x=>x.id===item.id),item.id+' under '+setting);}
 const normalized=items=>Array.from(items,x=>x.id).sort();
 l.settings.clear();l.settings.add('village');l.settings.add('underground');assert.deepEqual(normalized(t.visibleLocations()),normalized(templates.filter(x=>x.settings.some(s=>['village','underground'].includes(s)))));
 l.conditions.add('maintained');l.conditions.add('ruined');assert.deepEqual(normalized(t.visibleLocations()),normalized(templates.filter(x=>x.settings.some(s=>['village','underground'].includes(s))&&['maintained','ruined'].includes(x.condition))));assert(t.visibleLocations().every(x=>x.condition!==null));
 t.clearLocationFilters();l.conditions.add('abandoned');assert.deepEqual(normalized(t.visibleLocations()),templates.filter(x=>x.condition==='abandoned').map(x=>x.id).sort());t.clearLocationFilters();l.conditions.add('ruined');assert.deepEqual(normalized(t.visibleLocations()),['overgrown-homestead']);t.clearLocationFilters();
 const search=w.document.querySelector('#location-search');search.value='portcullis';search.dispatchEvent(new w.Event('input'));assert.deepEqual(normalized(t.visibleLocations()),['gatehouse']);
 const setting=w.document.querySelector('#setting-options input[value="village"]');setting.checked=true;setting.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.document.querySelectorAll('.location-card').length,0);w.document.querySelector('#location-grid .empty-state button').click();assert.equal(search.value,'');assert.equal(t.visibleLocations().length,templates.length);assert.equal(w.document.querySelectorAll('#location-filter-panel input:checked').length,0);
 const toggle=w.document.querySelector('#location-filter-toggle');toggle.click();assert.equal(toggle.getAttribute('aria-expanded'),'true');assert(w.document.querySelector('#location-filter-panel').classList.contains('open'));toggle.click();assert.equal(toggle.getAttribute('aria-expanded'),'false');
 const original=JSON.stringify(l.templates[0]);w.document.querySelector('[data-template-id="inn"] button').click();w.document.querySelector('[data-template-id="inn"] button').click();assert.equal(l.instances.length,2);assert.notEqual(l.instances[0].id,l.instances[1].id);assert.notEqual(l.instances[0].settings,l.instances[1].settings);
 t.setView('session');assert.equal(w.document.querySelectorAll('.session-location-card').length,2);assert.equal(w.document.querySelector('#session-location-count').textContent,'2 locations');assert.equal(w.document.querySelector('#cast-count').textContent,'1 NPCs');
 const card=w.document.querySelector('.session-location-card');const name=card.querySelector('input');name.value='<img src=x onerror=alert(1)> Silver Fox Inn';name.dispatchEvent(new w.Event('input'));const notes=card.querySelector('textarea');notes.value='Meet the captain. <script>alert(1)</script>';notes.dispatchEvent(new w.Event('input'));const condition=card.querySelector('select');condition.value='ruined';condition.dispatchEvent(new w.Event('input'));
 assert.equal(l.instances[0].condition,'ruined');assert.equal(l.instances[1].displayName,'Inn');assert.equal(l.instances[1].notes,'');assert.equal(l.instances[1].condition,'maintained');assert.equal(JSON.stringify(l.templates[0]),original);assert.equal(card.querySelectorAll('img,script').length,0);
 const persist={};for(let i=0;i<w.localStorage.length;i++){const k=w.localStorage.key(i);persist[k]=w.localStorage.getItem(k)};
 const refresh=await setup(persist);refresh.window.test.setView('session');assert.equal(refresh.window.test.locationLibrary.instances.length,2);assert.equal(refresh.window.document.querySelector('input[data-location-field="displayName"]').value,name.value);assert.equal(refresh.window.document.querySelector('textarea[data-location-field="notes"]').value,notes.value);assert.equal(refresh.window.document.querySelector('select[data-location-field="condition"]').value,'ruined');refresh.window.close();
 t.setView('generator');await t.ensureGenerator();w.document.querySelector('#add-generated').click();const result=JSON.stringify(t.generator.current),record=JSON.stringify(t.generator.records);t.setView('session');card.querySelector('button').click();assert.equal(l.instances.length,1);assert.equal(l.instances[0].displayName,'Inn');assert.equal(t.sessionEntries().length,2);assert.equal(JSON.stringify(t.generator.records),record);assert.equal(JSON.stringify(t.generator.current),result);
 assert.equal(w.localStorage.getItem('npc-beta-saved'),seed['npc-beta-saved']);assert.equal(w.localStorage.getItem('npc-beta-session'),seed['npc-beta-session']);
 t.setView('saved');assert.equal(w.document.querySelectorAll('.character-card').length,1);assert.equal(w.document.querySelector('.character-card h3').textContent,'Mira Fen');t.setView('library');assert.equal(w.document.querySelectorAll('.character-card').length,JSON.parse(fs.readFileSync('docs/data/characters/index.json')).length);
 assert(t.safeLocationImage('images/locations/inn.webp'));for(const path of ['../image.png','/image.png','https://example.com/image.png','data:image/png;base64,x'])assert(!t.safeLocationImage(path));
 const imgTemplate={...templates[0],image:'images/locations/missing.png',imageAlt:'Missing inn'};l.templates=[imgTemplate];t.setView('locations');const img=w.document.querySelector('#location-grid img');assert.equal(img.alt,'Missing inn');img.dispatchEvent(new w.Event('error'));assert.equal(w.document.querySelectorAll('#location-grid img').length,0);assert(w.document.querySelector('#location-grid svg'));dom.window.close();
 for(const failure of ['storage','unavailable']){const blocked=await setup(seed,failure);blocked.window.test.addSessionLocation(templates[0]);assert.equal(blocked.window.test.locationLibrary.instances.length,1);assert.match(blocked.window.document.querySelector('#storage-warning').textContent,/cannot be saved/);blocked.window.close();}
 const bad=await setup({...seed,'npc-beta:locations:v1:session':'{broken'});bad.window.test.addSessionLocation(templates[0]);assert.equal(bad.window.localStorage.getItem('npc-beta:locations:v1:session'),'{broken');bad.window.close();
 const failed=await setup(seed,'data');assert.match(failed.window.document.querySelector('#location-results-note').textContent,/could not be loaded/);assert.equal(failed.window.document.querySelector('#location-grid button').textContent,'Try again');failed.window.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('docs/'+url,'utf8'))});await failed.window.test.ensureLocations();assert.equal(failed.window.document.querySelectorAll('.location-card').length,templates.length);failed.window.close();
 console.log('PASS: location templates, every setting tag, OR/AND/search/clear, mobile filter controls, independent instances, edits, safe text, persistence, NPC/generator preservation, storage/data failures, image fallback');
})().catch(error=>{console.error(error);process.exit(1)});
