const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const templateCount = require('../docs/data/locations/templates.json').length;
(async () => {
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{if(!localStorage.getItem('locations-test-seeded')){localStorage.setItem('npc-beta-saved','["mira-fen"]');localStorage.setItem('npc-beta-session','["cassian-holt"]');localStorage.setItem('locations-test-seeded','yes');}});
 await page.goto('http://localhost:8000/docs/');await page.waitForSelector('.character-card');await page.locator('.desktop-nav [data-view="locations"]').click();await page.waitForSelector('.location-card');assert.equal(await page.locator('.location-card').count(),templateCount);
 await page.locator('#setting-options input[value="village"]').check();await page.locator('#setting-options input[value="underground"]').check();await page.locator('#condition-options input[value="maintained"]').check();assert(await page.locator('.location-card').count()>0);
 await page.locator('#location-search').fill('portcullis');assert.equal(await page.locator('.location-card').count(),0);await page.locator('#location-grid').getByRole('button',{name:'Clear filters'}).click();assert.equal(await page.locator('.location-card').count(),templateCount);
 await page.locator('[data-template-id="inn"] button').click();await page.locator('[data-template-id="inn"] button').click();await page.locator('.desktop-nav [data-view="session"]').click();assert.equal(await page.locator('.session-location-card').count(),2);
 const first=page.locator('.session-location-card').first();await first.locator('input').fill('Silver Fox Inn');await first.locator('textarea').fill('Meet the captain here.');await first.locator('select').selectOption('ruined');assert.equal(await page.locator('.session-location-card').last().locator('input').inputValue(),'Inn');
 await page.reload();await page.locator('.desktop-nav [data-view="session"]').click();assert.equal(await first.locator('input').inputValue(),'Silver Fox Inn');assert.equal(await first.locator('textarea').inputValue(),'Meet the captain here.');assert.equal(await first.locator('select').inputValue(),'ruined');await first.getByRole('button',{name:/Remove/}).click();assert.equal(await page.locator('.session-location-card').count(),1);assert.equal(await page.locator('#character-grid .cast-entry').count(),1);
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('npc-beta-saved'))),['mira-fen']);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('npc-beta-session'))),['cassian-holt']);
 for(const width of [320,375,480,600,760,900,1440]){await page.setViewportSize({width,height:900});for(const view of ['locations','library','saved','session','generator']){await page.evaluate(view=>setView(view),view);if(view==='generator')await page.waitForSelector('#generator-controls:not([hidden])');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${view} overflow at ${width}`);}}
 await page.setViewportSize({width:375,height:900});await page.locator('.bottom-nav [data-view="locations"]').click();await page.locator('#location-filter-toggle').click();assert.equal(await page.locator('#location-filter-toggle').getAttribute('aria-expanded'),'true');assert(await page.locator('#location-filter-panel').isVisible());
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: location browser integration, persistence and responsive overflow');
})().catch(error=>{console.error(error);process.exit(1)});
