const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const ids=['wizards-tower','ship','mine-quarry','academy-library','traveling-carnival'];
(async()=>{
const browser=await chromium.launch(process.env.NPC_TEST_CHROME?{executablePath:process.env.NPC_TEST_CHROME,args:['--no-sandbox']}:{}),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
if(process.env.NPC_TEST_LOCAL_FILES)await page.route('http://localhost:8000/**',async route=>{const path=new URL(route.request().url()).pathname;const file='.'+(path.endsWith('/')?path+'index.html':path);const type=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.webp')?'image/webp':'text/html';await route.fulfill({status:fs.existsSync(file)?200:404,contentType:type,body:fs.existsSync(file)?fs.readFileSync(file):'Not found'});});
await page.goto('http://localhost:8000/docs/');await page.waitForSelector('.character-card');await page.evaluate(()=>setView('generator'));await page.waitForFunction(()=>generator.current && locationLibrary.templates);
for(const width of [320,375,760,900,1440]){await page.setViewportSize({width,height:1000});for(const id of ids){await page.selectOption('#generator-location',id);await page.waitForFunction(()=>{const images=[...document.querySelectorAll('#generator-visual-preview img')];return images.every(x=>x.complete&&x.naturalWidth>0);});const visual=page.locator('#generator-visual-preview');assert((await visual.locator('.generated-visual-background img').getAttribute('src')).endsWith(id+'-location.webp'));assert(await visual.locator('.generated-npc-silhouette').isVisible());assert(await visual.locator('.generated-profession-badge').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}
for(const id of ids){await page.selectOption('#generator-location',id);await page.locator('[data-roll="name"]').click();await page.locator('#add-generated').click();}
await page.selectOption('#generator-location','wizards-tower');await page.selectOption('#generator-profession','mage');await page.evaluate(()=>{clearTimeout(announce.timer);document.querySelector('#action-feedback').textContent='';window.scrollTo(0,0);});fs.mkdirSync('project/screenshots',{recursive:true});await page.screenshot({path:'project/screenshots/missing-locations-generator.png'});
await page.evaluate(()=>setView('locations'));await page.waitForSelector('.location-card');assert.equal(await page.locator('.location-card').count(),44);assert.deepEqual(await page.locator('.location-card').evaluateAll(els=>els.slice(0,5).map(x=>x.dataset.templateId)),ids);await page.screenshot({path:'project/screenshots/missing-locations-library.png'});
for(const id of ids){await page.locator(`[data-template-id="${id}"] button`).click();}
await page.evaluate(()=>setView('session'));assert.equal(await page.locator('.session-location-card').count(),5);assert.equal(await page.locator('#character-grid .generated-npc-visual').count(),5);for(const id of ids)assert.equal(await page.locator(`#character-grid .generated-visual-background img[src$="${id}-location.webp"]`).count(),1);await page.evaluate(()=>{clearTimeout(announce.timer);document.querySelector('#action-feedback').textContent='';window.scrollTo(0,0);});await page.screenshot({path:'project/screenshots/missing-locations-session.png'});await page.setViewportSize({width:375,height:1000});await page.evaluate(()=>window.scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'project/screenshots/missing-locations-mobile.png'});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: all five generator images load at five widths, silhouette/badge visibility, recent library order/count, all five generated and location Session entries, mobile overflow, no page errors');
})().catch(e=>{console.error(e);process.exit(1)});
