const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const ids=['wizards-tower','ship','mine-quarry','academy-library','traveling-carnival'];
(async()=>{
const seed={'npc-beta-saved':'["mira-fen"]','npc-beta-session':'["cassian-holt"]','npc-beta:generator:v1:session':JSON.stringify([{id:'generated-tower',name:'Legacy Wizard',locationId:'wizards-tower',locationLabel:'Wizard’s tower',professionId:'mage',professionLabel:'Mage',createdAt:'2026-01-01'}])};
const w=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.com/',runScripts:'outside-only'}).window;w.scrollTo=()=>{};w.fetch=async p=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('docs/'+p))});for(const[k,v]of Object.entries(seed))w.localStorage.setItem(k,v);
w.eval(['portraits','character-portraits','generator','locations','generated-visuals','app'].map(n=>fs.readFileSync('docs/js/'+n+'.js','utf8')).join('\n')+'\nwindow.test={setView,ensureLocations,ensureGenerator,rollGenerator,generator,locationLibrary,visibleLocations,generatedNpcVisual,GENERATED_LOCATION_TEMPLATES};');
await new Promise(r=>setTimeout(r,30));const t=w.test,d=w.document;t.setView('locations');await t.ensureLocations();assert.equal(t.locationLibrary.templates.length,44);assert.deepEqual(Array.from(t.visibleLocations().slice(0,5),x=>x.id),ids);
const labels=JSON.parse(fs.readFileSync('docs/data/locations/labels.json'));
for(const id of ids){const template=t.locationLibrary.templates.find(x=>x.id===id);assert(template.description.length>60);assert(template.imageAlt);assert(template.settings.every(x=>Object.hasOwn(labels.settings,x)));assert.equal(template.condition,'maintained');assert(Number.isFinite(Date.parse(template.publishedAt)));assert.equal(t.GENERATED_LOCATION_TEMPLATES[id],id);assert(fs.existsSync('docs/'+template.image));d.querySelector(`[data-template-id="${id}"] button`).click();}
assert.deepEqual(Array.from(t.locationLibrary.instances,x=>x.templateId),ids);t.setView('session');assert.equal(d.querySelectorAll('.session-location-card').length,5);assert(d.querySelector('#character-grid .generated-visual-background img').src.endsWith('/wizards-tower-location.webp'));
t.setView('generator');await t.ensureGenerator();const options=JSON.parse(fs.readFileSync('docs/data/generator/options.json'));
for(const id of ids){t.rollGenerator('location',id);assert(options.locations.find(x=>x.id===id).professionIds.includes(t.generator.current.professionId));const visual=d.querySelector('#generator-visual-preview');assert(visual.querySelector('.generated-visual-background img').src.endsWith('/'+id+'-location.webp'));assert(visual.querySelector('.generated-npc-silhouette'));assert(visual.querySelector('.generated-profession-badge'));}
for(const[k,v]of Object.entries(seed))assert.equal(w.localStorage.getItem(k),v);w.close();console.log('PASS: five complete templates/artwork, recent order, settings/condition, independent location Sessions, existing generated tower records, all five generator backgrounds and compatible professions, Saved/NPC Session preservation');
})().catch(e=>{console.error(e);process.exit(1)});
