const {JSDOM}=require('jsdom');const fs=require('node:fs');const assert=require('node:assert/strict');
async function setup(configured=false,hash=""){const dom=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.com/npcbeta/'+hash,runScripts:'outside-only'});const w=dom.window;w.scrollTo=()=>{};w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=function(){this.scrolled=true};w.fetch=async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('docs/'+path))});w.localStorage.setItem('npc-beta-saved','["mira-fen"]');w.localStorage.setItem('npc-beta-session','["cassian-holt"]');w.eval(['portraits','generator','locations','pro','generated-visuals','app'].map(name=>{let code=fs.readFileSync('docs/js/'+name+'.js','utf8');return configured&&name==='pro'?code.replace('supportUrl: ""','supportUrl: "https://example.com/support"'):code}).join('\n'));await new Promise(r=>setTimeout(r,20));return dom;}
(async()=>{const dom=await setup(),w=dom.window,d=w.document;d.querySelector('.desktop-nav [data-view="support"]').click();assert(!d.querySelector('#pro-view').hidden);
 const labels=['Library','Locations','Name Generator','Saved','Session','Support Us'];
 for(const menu of ['.desktop-nav','.bottom-nav']) assert.deepEqual([...d.querySelectorAll(menu+' button')].map(b=>b.querySelector('span')?.textContent||b.textContent),labels);
 assert.equal(d.title,'Support NPC Beta — NPC Beta');assert(!/\bPro\b|premium|exclusive|paid upgrade/i.test(d.querySelector('#pro-view').textContent));
 assert.equal(d.querySelector('meta[name="description"]').content,'Patreon support helps keep NPC Beta’s NPCs, locations and tools free for every Game Master.');
 assert.equal(d.querySelector('.saved-count').textContent,'1');assert.equal(d.querySelector('.session-count').textContent,'1');
 for(const pending of d.querySelectorAll('[data-support]'))assert.equal(pending.textContent,'Patreon support coming soon');assert(d.querySelector('.library').hidden);assert.equal(d.querySelectorAll('.pro-badge').length,6);assert.equal(d.querySelectorAll('[data-support]').length,2);assert.equal(d.querySelectorAll('a.pro-support').length,0);assert.equal(d.querySelector('.desktop-nav [data-view="support"]').getAttribute('aria-current'),'page');d.querySelector('.pro-explore').click();assert.equal(d.activeElement.id,'pro-features');assert(d.activeElement.scrolled);d.querySelector('#pro-portrait').dispatchEvent(new w.Event('error'));assert(d.querySelector('#pro-portrait').hidden);d.querySelector('.desktop-nav [data-view="saved"]').click();assert(d.querySelector('#pro-view').hidden);assert.equal(d.querySelector('.character-card h3').textContent,'Mira Fen');assert.equal(w.localStorage.getItem('npc-beta-saved'),'["mira-fen"]');assert.equal(w.localStorage.getItem('npc-beta-session'),'["cassian-holt"]');dom.window.close();const configured=await setup(true);const links=[...configured.window.document.querySelectorAll('a.pro-support')];assert.equal(links.length,2);for(const link of links){assert.equal(link.href,'https://example.com/support');assert.equal(link.textContent,'Become a Patron');}configured.window.close();
 for(const hash of ['#pro','#support']){const routed=await setup(false,hash);assert(!routed.window.document.querySelector('#pro-view').hidden);assert.equal(routed.window.document.title,'Support NPC Beta — NPC Beta');routed.window.close();}
 console.log('PASS: Support Us navigation/order, titles/metadata, legacy/direct routes, counts, planned cards, pending/configured support, focus and scroll, artwork fallback, saved view and storage preservation');})().catch(e=>{console.error(e);process.exit(1)});
