const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.NPC_TEST_CHROME,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://localhost:8000/**',async route=>{const pathname=new URL(route.request().url()).pathname,file='.'+(pathname.endsWith('/')?pathname+'index.html':pathname);await route.fulfill({status:fs.existsSync(file)?200:404,contentType:({js:'text/javascript',css:'text/css',json:'application/json',svg:'image/svg+xml',webp:'image/webp'})[file.split('.').pop()]||'text/html',body:fs.existsSync(file)?fs.readFileSync(file):'Not found'});});
await page.goto('http://localhost:8000/docs/#locations');await page.waitForSelector('.location-card');
const data=JSON.parse(fs.readFileSync('docs/data/locations/templates.json')),ids=['campsite-with-fire','alleyway','farm'];assert.equal(new Set(data.map(x=>x.id)).size,data.length);
assert.deepEqual(await page.locator('.location-card').evaluateAll(ns=>ns.slice(0,3).map(n=>n.dataset.templateId)),ids);
for(const id of ids){const entry=data.find(x=>x.id===id);assert(fs.existsSync('docs/'+entry.image));const card=page.locator(`[data-template-id="${id}"]`);await card.locator('.location-card-open').click();assert.equal(await page.locator('#detail-title').textContent(),entry.name);assert((await page.locator('.location-introduction').textContent()).includes(entry.readAloud));await page.locator('.back-button').click();}
const card=page.locator('[data-template-id="campsite-with-fire"]');await card.hover();await page.waitForTimeout(450);assert.equal(await card.evaluate(n=>getComputedStyle(n).transform),'matrix(1, 0, 0, 1, 0, -3)');assert.equal(await card.locator('img').evaluate(n=>getComputedStyle(n).transform),'matrix(1.025, 0, 0, 1.025, 0, 0)');
await page.mouse.move(1420,940);await page.evaluate(()=>{clearTimeout(announce.timer);document.querySelector('#action-feedback').textContent='';});await page.waitForTimeout(450);fs.mkdirSync('project/screenshots',{recursive:true});await page.screenshot({path:'project/screenshots/rest-and-routes-desktop.png',fullPage:false});
await page.emulateMedia({reducedMotion:'reduce'});await card.hover();assert.equal(await card.evaluate(n=>getComputedStyle(n).transform),'none');
await page.setViewportSize({width:390,height:844});await page.mouse.move(0,0);await page.screenshot({path:'project/screenshots/rest-and-routes-mobile.png',fullPage:false});for(const width of [320,390,768]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: three new locations first in recent sort, complete modal content, image assets, exact hover lift/zoom, reduced motion, mobile sizing, zero browser errors');
})().catch(e=>{console.error(e);process.exit(1)});
