const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.NPC_TEST_CHROME,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://localhost:8000/**',async route=>{const pathname=new URL(route.request().url()).pathname,file='.'+(pathname.endsWith('/')?pathname+'index.html':pathname);await route.fulfill({status:fs.existsSync(file)?200:404,contentType:({js:'text/javascript',css:'text/css',json:'application/json',svg:'image/svg+xml',webp:'image/webp'})[file.split('.').pop()]||'text/html',body:fs.existsSync(file)?fs.readFileSync(file):'Not found'});});
await page.goto('http://localhost:8000/docs/');await page.waitForSelector('.character-card');
await page.evaluate(()=>{localStorage.setItem('npc-beta-session','["mira-fen","cassian-holt","brother-alden","nessa-vale"]');localStorage.setItem('npc-beta:locations:v1:session',JSON.stringify(['tavern','market-square','watchhouse'].map((templateId,i)=>({id:'location-'+i,templateId,displayName:['Copper Lantern Tavern','Market Square','Watchhouse'][i],notes:'Existing notes',settings:['town'],condition:null,createdAt:new Date().toISOString()}))));});
await page.goto('http://localhost:8000/docs/#session');await page.reload();await page.waitForSelector('[data-entry-id="location-0"]');
const action=(id,a)=>page.locator(`[data-entry-id="${id}"] [data-session-action="${a}"]`);
await action('cassian-holt','assign').click();await action('mira-fen','assign').click();await action('location-1','active').click();await action('cassian-holt','assign').click();await page.reload();await page.waitForSelector('.is-active-location');
assert.equal(await page.locator('.is-active-location').getAttribute('data-entry-id'),'location-1');assert.equal(await page.locator('.location-cast-member').count(),3);assert(await action('cassian-holt','assign').isDisabled());
await action('location-0','active').click();await page.locator('#session-search').fill('no match');assert.equal(await page.locator('.session-assign-button').count(),0);await page.locator('#session-clear-search').click();
await page.locator('.location-cast-profile').first().click();assert.equal(await page.locator('#detail-panel').getAttribute('aria-hidden'),'false');assert(await page.locator('.session-button').isHidden());await page.keyboard.press('Escape');
fs.mkdirSync('project/screenshots',{recursive:true});await page.mouse.move(1430,930);await page.screenshot({path:'project/screenshots/session-location-cast-desktop.png',fullPage:true});
for(const width of [320,390,760,768,1024,1440]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);assert(await page.locator('#session-locations').isVisible());assert(await page.locator('#session-npc-column').isVisible());}
await page.setViewportSize({width:390,height:844});assert(await page.locator('#session-locations').evaluate((n)=>n.getBoundingClientRect().top)<await page.locator('#session-npc-column').evaluate((n)=>n.getBoundingClientRect().top));await page.screenshot({path:'project/screenshots/session-location-cast-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS browser: assignments/reload/active location, multiple membership, profile modal, search, stacked mobile, 320–1440px no overflow; screenshots saved');
})().catch(e=>{console.error(e);process.exit(1)});
