const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.NPC_TEST_CHROME,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://localhost:8000/**',async route=>{const pathname=new URL(route.request().url()).pathname,file='.'+(pathname.endsWith('/')?pathname+'index.html':pathname);const ext=file.split('.').pop();await route.fulfill({status:fs.existsSync(file)?200:404,contentType:({js:'text/javascript',css:'text/css',json:'application/json',svg:'image/svg+xml',webp:'image/webp',png:'image/png'})[ext]||'text/html',body:fs.existsSync(file)?fs.readFileSync(file):'Not found'});});
await page.goto('http://localhost:8000/docs/');await page.waitForSelector('.character-card');
await page.evaluate(()=>{
 localStorage.setItem('npc-beta-session',JSON.stringify(['harl-mercer','mara-flint','mira-fen','cassian-holt','jory-pike','bess-crowley']));localStorage.setItem('npc-beta-saved','["mira-fen"]');
 localStorage.setItem('npc-beta:generator:v1:session',JSON.stringify([{id:'generated-test',name:'Edwin Ash',professionId:'blacksmith',professionLabel:'Blacksmith',locationId:'tavern-inn',locationLabel:'Tavern / Inn',createdAt:'2026-10-09'}]));
 localStorage.setItem('npc-beta:locations:v1:session',JSON.stringify(['tavern','inn','market-square'].map((id,i)=>({id:'location-'+i,templateId:id,displayName:['The Bent Nail','Silver Fox Inn','Market Square'][i],notes:'Existing notes '+i,settings:['village'],condition:'maintained',createdAt:'2026-10-09'}))));location.hash='session';
});await page.reload();await page.waitForSelector('#character-grid .session-row');await page.waitForFunction(()=>locationLibrary.templates);
const ids=()=>page.locator('#character-grid .session-row').evaluateAll(rows=>rows.map(r=>r.dataset.entryId));const original=await ids();assert.equal(original.length,7);
const oldStorage=await page.evaluate(()=>['npc-beta-session','npc-beta-saved','npc-beta:generator:v1:session','npc-beta:locations:v1:session'].map(k=>localStorage.getItem(k)));
const pin=page.locator('[data-entry-id="mira-fen"] [data-session-action=pin]');await pin.click();assert.equal((await ids())[0],'mira-fen');assert.deepEqual((await ids()).slice(1),original.filter(id=>id!=='mira-fen'));assert.equal(await page.locator('#detail-panel').getAttribute('aria-hidden'),'true');await page.locator('[data-entry-id="location-1"] [data-session-action=pin]').click();assert.equal(await page.locator('#session-location-list .session-row').first().getAttribute('data-entry-id'),'location-1');
await page.reload();await page.waitForSelector('.is-pinned');assert.equal((await ids())[0],'mira-fen');assert.deepEqual(await page.evaluate(()=>['npc-beta-session','npc-beta-saved','npc-beta:generator:v1:session','npc-beta:locations:v1:session'].map(k=>localStorage.getItem(k))),oldStorage);
await page.locator('#session-search').fill('blacksmith');assert(await page.locator('#character-grid .session-row').count());assert.equal(await page.locator('#session-location-list .session-row').count(),0);await page.locator('#session-search').fill('Silver Fox');assert.equal(await page.locator('#character-grid .session-row').count(),0);assert.equal(await page.locator('#session-location-list .session-row').count(),1);await page.locator('#session-search').fill('travelers');assert.equal(await page.locator('#session-location-list .session-row').count(),1);await page.locator('#session-search').fill('no-such-match');assert.equal(await page.locator('#session-board .empty-state').count(),2);await page.locator('#session-clear-search').click();
const image=page.locator('[data-entry-id="mira-fen"] .session-portrait');await page.mouse.move(1400,890);assert.equal(await image.evaluate(n=>getComputedStyle(n).filter),'grayscale(1)');await page.locator('[data-entry-id="mira-fen"] .session-row-open').focus();assert.equal(await image.evaluate(n=>getComputedStyle(n).filter),'none');
const opener=page.locator('[data-entry-id="mira-fen"] .session-row-open');await opener.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.detail-content h2').textContent(),'Mira Fen');assert(await page.locator('.session-button').isHidden());assert.equal(await page.locator('.detail-scroll').evaluate(n=>n.scrollTop),0);await page.keyboard.press('Escape');assert(await opener.evaluate(n=>n===document.activeElement));
await page.locator('[data-entry-id="generated-test"] .session-row-open').click();assert(await page.locator('.detail-extra-visual .generated-npc-silhouette').isVisible());assert(await page.locator('.session-button').isHidden());await page.keyboard.press('Escape');
await page.locator('[data-entry-id="location-1"] .session-row-open').click();assert.equal(await page.locator('[data-location-field=notes]').inputValue(),'Existing notes 1');await page.locator('[data-location-field=notes]').fill('Updated existing notes');await page.keyboard.press('Escape');
await page.evaluate(()=>document.querySelector('#action-feedback').textContent='').catch(()=>{});await page.waitForTimeout(30);await page.evaluate(()=>document.querySelector('#action-feedback').textContent='');await page.mouse.move(1400,890);fs.mkdirSync('project/screenshots',{recursive:true});await page.screenshot({path:'project/screenshots/session-board-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('#session-locations').hidden);assert(await page.locator('#session-locations').isHidden());assert(await page.locator('#session-tab-npcs').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#session-tab-npcs').focus();await page.keyboard.press('ArrowRight');assert(await page.locator('#session-npc-column').isHidden());assert(await page.locator('#session-locations').isVisible());await page.screenshot({path:'project/screenshots/session-board-mobile-locations.png',fullPage:true});await page.locator('#session-tab-npcs').click();await page.screenshot({path:'project/screenshots/session-board-mobile.png',fullPage:true});
for(const width of [320,760,768,1024]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);}
await page.setViewportSize({width:390,height:844});await page.locator('#session-tab-npcs').click();const targets=await page.locator('#session-npc-column .session-row-actions button').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));assert(targets.every(h=>h>=44));
await page.locator('[data-entry-id="mira-fen"] [data-session-action=pin]').click();assert.deepEqual(await ids(),original);await page.locator('[data-entry-id="generated-test"] [data-session-action=remove]').click();assert.equal(await page.locator('[data-entry-id="generated-test"]').count(),0);assert.equal(await page.locator('#detail-panel').getAttribute('aria-hidden'),'true');await page.locator('#session-tab-locations').click();await page.locator('[data-entry-id="location-0"] [data-session-action=remove]').click();await page.reload();await page.waitForSelector('#character-grid .session-row');assert.equal(await page.locator('[data-entry-id="location-0"]').count(),0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('npc-beta:locations:v1:session')).find(x=>x.id==='location-1').notes),'Updated existing notes');
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.detail-panel').evaluate(n=>getComputedStyle(n).transitionDuration),'0s');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: mixed Session, stable pin ordering/reload, original storage, search/clear/empty results, native keyboard profiles, generated visual, location notes, removals/reload, mobile tabs, 320–1440px overflow, 44px controls, reduced motion; screenshots saved');
})().catch(e=>{console.error(e);process.exit(1)});
