const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
async function setup(seed={}){
const dom=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.com/#session',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};
for(const [k,v] of Object.entries(seed))w.localStorage.setItem(k,v);
w.fetch=async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('docs/'+path))});w.eval(['portraits','character-portraits','generator','locations','generated-visuals','session-board','app'].map(n=>fs.readFileSync('docs/js/'+n+'.js','utf8')).join('\n')+'\nwindow.test={boardEntries,moveSessionLocation,locationLibrary,addSessionLocation,setView,sessionBoard,renderSessionBoard};');await new Promise(r=>setTimeout(r,30));return {dom,w,d:w.document,t:w.test};}
const key='npc-beta:locations:v1:session',pins='npc-beta:session-board:v1:pins',order='npc-beta:session-board:v1:location-order';
const records=['a','b','c','d','e'].map(id=>({id:'location-'+id,templateId:'inn',displayName:id.toUpperCase(),notes:'Notes '+id,settings:['village'],condition:'maintained',createdAt:'2026-01-01'}));
const seed={[key]:JSON.stringify(records),[pins]:JSON.stringify({npcs:['mira-fen'],locations:['location-c','location-a']}),'npc-beta-session':'["mira-fen","cassian-holt"]','npc-beta-saved':'["mira-fen"]'};
(async()=>{
const {dom,w,d,t}=await setup(seed);const ids=()=>Array.from(t.boardEntries('locations'),x=>x.id.replace('location-',''));const action=(id,a)=>d.querySelector(`[data-entry-id="location-${id}"] [data-session-action="${a}"]`);const npcOrder=Array.from(d.querySelectorAll('#character-grid .session-row'),x=>x.dataset.entryId);
assert.deepEqual(ids(),['a','c','b','d','e']);assert.equal(w.localStorage.getItem(order),null);assert(action('a','up').disabled);assert(action('c','down').disabled);assert(action('b','up').disabled);assert(action('e','down').disabled);
action('e','up').click();assert.deepEqual(ids(),['a','c','b','e','d']);action('c','up').click();assert.deepEqual(ids(),['c','a','b','e','d']);assert.equal(d.querySelector('#detail-panel').getAttribute('aria-hidden'),'true');
action('c','pin').click();assert.deepEqual(ids(),['a','b','e','d','c']);action('e','pin').click();assert.deepEqual(ids(),['a','e','b','d','c']);action('a','pin').click();assert.deepEqual(ids(),['e','b','d','c','a']);
assert.equal(w.localStorage.getItem(key),seed[key]);assert.deepEqual(Array.from(d.querySelectorAll('#character-grid .session-row'),x=>x.dataset.entryId),npcOrder);
t.sessionBoard.query='Inn';t.renderSessionBoard();assert(!d.querySelector('#session-location-reorder-note').hidden);for(const n of d.querySelectorAll('[data-session-action=up], [data-session-action=down], .session-location-drag'))assert(n.disabled);const before=ids();t.moveSessionLocation('location-d',1);assert.deepEqual(ids(),before);t.sessionBoard.query='';t.renderSessionBoard();
t.setView('locations');t.addSessionLocation(t.locationLibrary.templates.find(x=>x.id==='inn'));t.setView('session');assert.equal(t.boardEntries('locations').at(-1).displayName,'Inn');assert.equal(t.boardEntries('locations')[0].id,'location-e');
action('d','remove').click();assert.deepEqual(JSON.parse(JSON.stringify(t.locationLibrary.instances.filter(x=>x.id.startsWith('location-')&&x.id.length===10))),records.filter(x=>x.id!=='location-d'));
const persisted={};for(let i=0;i<w.localStorage.length;i++){const k=w.localStorage.key(i);persisted[k]=w.localStorage.getItem(k);}const reload=await setup(persisted);assert.deepEqual(Array.from(reload.t.boardEntries('locations'),x=>x.id),Array.from(t.boardEntries('locations'),x=>x.id));reload.dom.window.close();assert.equal(w.localStorage.getItem('npc-beta-session'),seed['npc-beta-session']);assert.equal(w.localStorage.getItem('npc-beta-saved'),seed['npc-beta-saved']);dom.window.close();
for(const value of ['{broken','["location-a","location-a"]','null']){const x=await setup({...seed,[order]:value});x.t.moveSessionLocation('location-e',-1);assert.equal(x.w.localStorage.getItem(order),value);assert.equal(x.w.localStorage.getItem(key),seed[key]);x.dom.window.close();}
for(const count of [0,1]){const x=await setup({[key]:JSON.stringify(records.slice(0,count))});assert.equal(x.d.querySelectorAll('.session-location-order-row').length,count);for(const n of x.d.querySelectorAll('.session-location-drag,[data-session-action=up],[data-session-action=down]'))assert(n.disabled);x.dom.window.close();}
console.log('PASS: legacy ordering/group boundaries, moves, destination-tail pin transitions, adding/removing, reload, search guards, NPC order/storage, intact names/notes/IDs, malformed-order protection and zero/one location');
})().catch(e=>{console.error(e);process.exit(1)});
