const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.NPC_TEST_CHROME,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://localhost:8000/**',async route=>{const path=new URL(route.request().url()).pathname,file='.'+(path.endsWith('/')?path+'index.html':path),ext=file.split('.').pop();await route.fulfill({status:fs.existsSync(file)?200:404,contentType:({js:'text/javascript',css:'text/css',json:'application/json',svg:'image/svg+xml',webp:'image/webp'})[ext]||'text/html',body:fs.existsSync(file)?fs.readFileSync(file):'Not found'});});
await page.goto('http://localhost:8000/docs/');await page.waitForSelector('.character-card');
await page.evaluate(()=>{localStorage.setItem('npc-beta-session','["mira-fen","cassian-holt"]');localStorage.setItem('npc-beta-saved','["mira-fen"]');localStorage.setItem('npc-beta:session-board:v1:pins',JSON.stringify({npcs:['mira-fen'],locations:['location-a','location-c']}));localStorage.setItem('npc-beta:locations:v1:session',JSON.stringify(['a','b','c','d','e'].map(id=>({id:'location-'+id,templateId:'inn',displayName:id.toUpperCase()+' Inn',notes:'Original notes '+id,settings:['village'],condition:'maintained',createdAt:'2026-01-01'}))));location.hash='session';});await page.reload();await page.waitForSelector('#character-grid .session-row');await page.waitForFunction(()=>locationLibrary.templates);
const ids=()=>page.locator('#session-location-list .session-row').evaluateAll(rows=>rows.map(r=>r.dataset.entryId.replace('location-',''))),row=id=>page.locator(`[data-entry-id="location-${id}"]`),button=(id,action)=>row(id).locator(`[data-session-action="${action}"]`);
const npcOrder=await page.locator('#character-grid .session-row').evaluateAll(ns=>ns.map(n=>n.dataset.entryId)),original=await page.evaluate(()=>localStorage.getItem('npc-beta:locations:v1:session')),libraryOrder=await page.evaluate(()=>visibleLocations().map(x=>x.id));
assert.deepEqual(await ids(),['a','c','b','d','e']);assert(await button('a','up').isDisabled());assert(await button('c','down').isDisabled());assert(await button('b','up').isDisabled());assert(await button('e','down').isDisabled());
await button('c','drag').dragTo(row('a'),{targetPosition:{x:60,y:8}});assert.deepEqual(await ids(),['c','a','b','d','e']);await button('c','drag').dragTo(row('a'),{targetPosition:{x:60,y:90}});assert.deepEqual(await ids(),['a','c','b','d','e']);await button('c','drag').dragTo(row('a'),{targetPosition:{x:60,y:8}});assert.deepEqual(await ids(),['c','a','b','d','e']);await button('e','drag').dragTo(row('b'),{targetPosition:{x:60,y:8}});assert.deepEqual(await ids(),['c','a','e','b','d']);await button('c','drag').dragTo(row('b'),{targetPosition:{x:60,y:8}});assert.deepEqual(await ids(),['c','a','e','b','d']);assert.equal(await page.locator('#detail-panel').getAttribute('aria-hidden'),'true');
await button('e','down').focus();await page.keyboard.press('Space');assert.deepEqual(await ids(),['c','a','b','e','d']);assert(await button('e','down').evaluate(n=>document.activeElement===n));await page.keyboard.press('Enter');assert.deepEqual(await ids(),['c','a','b','d','e']);
await button('c','pin').click();assert.deepEqual(await ids(),['a','b','d','e','c']);await button('d','pin').click();assert.deepEqual(await ids(),['a','d','b','e','c']);await button('a','pin').click();assert.deepEqual(await ids(),['d','b','e','c','a']);assert.equal(await page.evaluate(()=>localStorage.getItem('npc-beta:locations:v1:session')),original);
await page.locator('#session-search').fill('A Inn');assert(await page.locator('#session-location-reorder-note').isVisible());assert.equal(await page.locator('#session-location-reorder-note').textContent(),'Clear search to reorder locations.');assert(await button('a','up').isDisabled());assert(await button('a','down').isDisabled());assert.equal(await button('a','drag').getAttribute('draggable'),'false');await page.locator('#session-clear-search').click();
await page.evaluate(()=>setView('locations'));await page.locator('[data-template-id="inn"] [data-location-add]').click();await page.evaluate(()=>setView('session'));assert.equal(await page.locator('#session-location-list .session-row h3').last().textContent(),'Inn');const beforeReload=await ids();await page.reload();await page.waitForSelector('#character-grid .session-row');assert.deepEqual(await ids(),beforeReload);await page.evaluate(()=>setView('library'));await page.evaluate(()=>setView('session'));assert.deepEqual(await ids(),beforeReload);assert.deepEqual(await page.evaluate(()=>visibleLocations().map(x=>x.id)),libraryOrder);
await row('c').locator('.session-row-open').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#detail-title').textContent(),'C Inn');assert.equal(await page.locator('[data-location-field=notes]').inputValue(),'Original notes c');assert(await page.locator('.session-button').isHidden());await page.keyboard.press('Escape');await button('e','remove').click();assert(!((await ids()).includes('e')));assert.equal(await page.locator('#detail-panel').getAttribute('aria-hidden'),'true');
await page.setViewportSize({width:390,height:844});await page.locator('#session-tab-locations').click();assert(await button('a','drag').isHidden());await button('a','up').click();assert.deepEqual((await ids()).slice(0,4),['d','b','a','c']);await button('a','down').focus();await page.keyboard.press('Enter');assert.deepEqual((await ids()).slice(0,4),['d','b','c','a']);
for(const width of [320,390,760,768,1024,1440]){await page.setViewportSize({width,height:900});await page.locator('#session-tab-locations').evaluate(n=>n.click());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);const sizes=await page.locator('#session-location-list [data-session-action=up],#session-location-list [data-session-action=down]').evaluateAll(ns=>ns.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));assert(sizes.every(s=>s.w>=44&&s.h>=44));}
await page.evaluate(()=>{clearTimeout(announce.timer);document.querySelector('#action-feedback').textContent='';});fs.mkdirSync('project/screenshots',{recursive:true});await page.screenshot({path:'project/screenshots/session-location-order-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('#session-tab-locations').click();await page.screenshot({path:'project/screenshots/session-location-order-mobile.png'});
assert.deepEqual(await page.locator('#character-grid .session-row').evaluateAll(ns=>ns.map(n=>n.dataset.entryId)),npcOrder);assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('npc-beta-session'),localStorage.getItem('npc-beta-saved'),JSON.parse(localStorage.getItem('npc-beta:session-board:v1:pins')).npcs]),['["mira-fen","cassian-holt"]','["mira-fen"]',['mira-fen']]);
while(await page.locator('#session-location-list .session-row').count()>1)await page.locator('#session-location-list [data-session-action=remove]').last().click();assert(await page.locator('#session-location-list [data-session-action=up]').isDisabled());assert(await page.locator('#session-location-list [data-session-action=down]').isDisabled());await page.locator('#session-location-list [data-session-action=remove]').click();assert.equal(await page.locator('#session-location-list .session-row').count(),0);assert(await page.locator('#session-location-list .empty-state').isVisible());await page.reload();await page.waitForSelector('#character-grid .session-row');await page.locator('#session-tab-locations').click();assert.equal(await page.locator('#session-location-list .session-row').count(),0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: native desktop dragging and cross-group rejection, move boundaries/keyboard/mobile, destination-tail pinning, search lock, add/remove, reload/return, profile opening, intact notes/NPC pins/order/storage/library sort, 320–1440px layout, 44px targets, zero/one location');
})().catch(e=>{console.error(e);process.exit(1)});
